### ISSUE TITLE
Multiple issues with modal navigation

### ISSUE THREAD

**Issue by neilt6** [PrismLibrary/Prism.Maui#106] opened 2022-08-23 21:58 UTC
### Problem 1: Navigation service is unable to perform modal navigation.
Attempting to navigate to a modal page using the following code snippet performs modeless navigation instead:

```
// Navigate to the modal page
await _navigationService.CreateBuilder()
    .AddNavigationPage(useModalNavigation: true)
    .AddSegment<ModalPageViewModel>()
    .NavigateAsync();
```

This is due to the code that determines the value of `useModalNavigation` being commented out in `PageNavigationService.ProcessNavigation`. Uncommenting this line resolves the issue:

```
protected virtual async Task ProcessNavigation(Page currentPage, Queue<string> segments, INavigationParameters parameters, bool? useModalNavigation, bool animated)
{
    ...

    //var useModalNavigation = pageParameters.ContainsKey(KnownNavigationParameters.UseModalNavigation) ? pageParameters.GetValue<bool>(KnownNavigationParameters.UseModalNavigation) : false;

    ...
}
```

### Problem 2: Navigation service is unable to return from modal navigation page.
Attempting to return from the previous modal page using the following code snippet fails:

```
// Close the modal page
await _navigationService.GoBackAsync();
```
```
[DOTNET] Navigation: GoBack
[DOTNET] Result: Failed
[DOTNET] Cannot GoBack from NavigationPage Root.
```

This is due to `PageNavigationService.GoBackModal` returning `false` when it should return `true`. I believe the following code should check if `navPage.Parent` is a `PrismWindow` instead of an `Application`. Changing this line resolves the issue:

```
private bool GoBackModal(NavigationPage navPage)
{
    ...

    else if (navPage.CurrentPage == navPage.RootPage && navPage.Parent is Application && rootPage != navPage)
        return true;

    ...
}
```

**Comment by sact1909** [comment] 2022-08-24 03:42
I have the same problem using GoBackAsync() trying to go back from Page B to Page A (or Root Page) in android, the application just blow out 

// Back to the main page
await _navigationService.GoBackAsync();

**Comment by dansiegel** [comment] 2022-08-24 04:45
Before I can look at this I will need a sample that reproduces the issue.

**Comment by developer9969** [comment] 2022-09-10 05:56
Hi  mine is a simple question that is sort of related to Modal navigation and noticed this issue too.

Is UseModalNavigation no longer part of the navigateAsync? In XF I could do 

         await navigationService.NavigateAsync("MyPageUri", useModalNavigation: true);

now is no longer possible and seems we need to use the new syntax below:  Is this correct?

          await _navigationService.CreateBuilder()
              .AddNavigationPage(useModalNavigation: true)
              .AddSegment<MyPageViewModel>()
              .NavigateAsync();

Many thanks

**Comment by dansiegel** [comment] 2022-09-10 14:10
@developer9969 the extension that you referenced was deprecated long ago and kept in Prism.Forms for backward compatibility reasons. If you evaluated:

```cs
var uri = _navigationService.CreateBuilder()
          .AddNavigationPage(useModalNavigation: true)
          .AddSegment<MyPageViewModel>()
          .Uri;
```

Then you would see that all it's doing is adding the Known Navigation Parameter to the Navigation Uri so that the appropriate page is navigated to Modally.

```
NavigationPage?useModalNavigation=true/MyPage

MyPage?useModalNavigation=true
```

@neilt6 I haven't forgotten this, I did just move though so I will get to it as soon as I can.

**Comment by developer9969** [comment] 2022-09-11 05:16
@dansiegel  thanks for replying.. getting familiar with Prism Maui and how to move our existing apps to Prism Maui and I can see now how you build the uri for modal navigation. ..  

Just re-reading your docs now and explanation about the navigation builder and AddSegment etc..  

thanks

**Comment by dansiegel** [comment] 2022-12-24 19:22
closing as no specific repo was provided. This seems to be more of an awareness issue with how the Navigation Service works.

**Closed by dansiegel** 2022-12-24 19:22 UTC
Labels: bug, to verify

**Comment by neilt6** [comment] 2022-12-24 20:39
@dansiegel I provided a documented sample as an attachment on August 24th. I believe this is bug, not an awareness issue.

That being said, I’ve abandoned my efforts with .NET MAUI for the time being.

**Comment by dansiegel** [comment] 2022-12-24 21:47
You attached a zip of the Prism Maui repo which is unacceptable for a reproduction of a reported issue.

**Comment by neilt6** [comment] 2022-12-24 22:02
@dansiegel The attached zip contained a modified version of _PrismMauiDemo_ to reproduce the issue. The relevant bits were documented by source comments in `MauiProgram`, `ModalPageViewModel`, and `RootPageViewModel` as indicated in the original comment. If this was unacceptable, you could have asked for an alternative submission at any point in the last 4 months.

As I said, I’ve abandoned .NET MAUI for now, so I’m not going to revisit this.
